package com.agnostix.activent.activent;

import android.provider.BaseColumns;

/**
 * Created by Shivam on 11/11/2014.
 */
public abstract class MacMapping {

    public static final String[][] macMap = new String[][]{


            {"c4:0a:cb:5c:0b:f", "ACB Ground floor Cafeteria (Glass Room)", "Academic Block"},
            {"c4:0a:cb:2d:97:1", "ACB Ground floor Cafeteria", "Academic Block"},
            {"c4:0a:cb:2d:c6:0", "Academic Block 1st Floor A Wing", "Academic Block"},
            {"c4:0a:cb:2d:ce:8", "Academic First Floor Middle", "Academic Block"},
            {"c4:0a:cb:25:c6:c", "Academic Block 1st Floor B Wing", "Academic Block"},
            {"c4:0a:cb:2d:bb:d", "New Sever Room", "Academic Block"},
            {"c4:0a:cb:2d:78:0", "Academic Block 2nd floor A Wing", "Academic Block"},
            {"c4:0a:cb:2d:82:f", "Academic Block Second Floor Middle", "Academic Block"},
            {"c4:0a:cb:25:d8:2", "Academic Block 2nd floor B Wing", "Academic Block"},
            {"c4:0a:cb:5c:07:0", "Academic Block 3rd Floor B Wing", "Academic Block"},
            {"c4:0a:cb:2d:75:5", "Academic Third Floor Middle", "Academic Block"},
            {"c4:0a:cb:25:bf:7", "Academic Block 3rd Floor A Wing", "Academic Block"},
            {"c4:0a:cb:25:e4:8", "Academic Block 4th Floor B Wing", "Academic Block"},
            {"c4:0a:cb:25:c4:4", "Academic Forth Floor Middile side", "Academic Block"},
            {"c4:0a:cb:2c:fa:d", "Academic Block 4th Floor A Wing", "Academic Block"},
            {"c4:0a:cb:2d:bb:e", "New PHD LAB 4th floor A wing", "Academic Block"},
            {"c4:0a:cb:5c:20:9", "Academic Block Fifth Floor A Wing", "Academic Block"},
            {"c4:0a:cb:2c:f4:6", "Academic Block Fifth Floor B Wing", "Academic Block"},
            {"c4:0a:cb:25:a8:3", "Academic Block 5'th Floor Middle", "Academic Block"},

            {"c4:0a:cb:5c:14:c", "C01(Back Side)", "Lecture Block"},
            {"c4:0a:cb:25:bb:7", "C02", "Lecture Block"},
            {"c4:0a:cb:25:b5:a", "C03", "Lecture Block"},
            {"c4:0a:cb:2d:71:2", "C01(Near Projector)", "Lecture Block"},
            {"2c:3e:cf:8f:57:3", "C01 left side", "Lecture Block"},
            {"2c:3e:cf:8f:52:6", "C01 right side", "Lecture Block"},
            {"c4:0a:cb:25:f2:d", "C11(Back Side)", "Lecture Block"},
            {"c4:0a:cb:2d:48:2", "C12", "Lecture Block"},
            {"c4:0a:cb:2d:c6:3", "C13", "Lecture Block"},
            {"c4:0a:cb:2d:aa:4", "C11(Near Projector)", "Lecture Block"},
            {"c4:0a:cb:5c:0f:1", "C24", "Lecture Block"},
            {"c4:0a:cb:2c:e6:2", "C23", "Lecture Block"},
            {"c4:0a:cb:2d:7d:5", "C22", "Lecture Block"},
            {"c4:0a:cb:2d:d4:d", "C21(Near Projector Screen)", "Lecture Block"},
            {"c4:0a:cb:25:cf:5", "Lecture hall C21(Backside)", "Lecture Block"},

            {"c4:0a:cb:25:b5:5", "Library Building Ground Floor", "Library"},
            {"c4:0a:cb:2d:95:a", "Library Block Ground Floor", "Library"},
            {"c4:0a:cb:2d:af:0", "Library Block Ground Floor", "Library"},
            {"c4:0a:cb:25:ce:6", "Library Block 1st floor(Near Reading Area)", "Library"},
            {"c4:0a:cb:5c:11:f", "Library Block First Floor(Near Asst. Mgr Library Office)", "Library"},
            {"c4:0a:cb:25:f6:a", "Library Building 1'st Floor Middle", "Library"},
            {"c4:0a:cb:2d:a4:1", "Library second floor (Near L23 in Gallary)", "Library"},
            {"c4:0a:cb:25:b7:6", "Library second floor (Near L21 in Gallary)", "Library"},
            {"c4:0a:cb:25:f3:5", "Library second floor (Near L22 in Gallary)", "Library"},
            {"b0:00:b4:20:6b:f", "Inside Lab21", "Library"},
            {"2c:3e:cf:b6:be:a", "Inside Lab22", "Library"},
            {"2c:3e:cf:4a:de:2", "Inside Lab23", "Library"},
            {"c4:0a:cb:25:b1:a", "Library 3rd Floor(Near L33 in Gallary)", "Library"},
            {"c4:0a:cb:2d:61:3", "Library 3rd Floor(Near L31 in Gallary)", "Library"},
            {"c4:0a:cb:25:e6:3", "Library 3rd Floor Middle in Gallary", "Library"},

            {"c4:0a:cb:5c:10:e", "Dining Block Ground floor", "Students Center"},
            {"c4:0a:cb:2d:84:0", "Dining Block Ground Floor", "Students Center"},
            {"c4:0a:cb:25:ff:5", "Dining Block GF cafeteria", "Students Center"},
            {"c4:0a:cb:2d:c4:8", "Dining Block First Floor", "Students Center"},
            {"c4:0a:cb:2d:84:e", "Dining Block Second Floor", "Students Center"},
            {"c4:0a:cb:5c:03:2", "Dining Hall Third Floor", "Students Center"},

            {"c4:0a:cb:5c:19:5", "GIRLS HOSTEL GROUND FLOOOR C Wing", "Girls Hostel"},
            {"c4:0a:cb:2d:7a:f", "GIRLS HOSTEL GROUND FLOOOR A Wing", "Girls Hostel"},
            {"c4:0a:cb:25:fd:1", "GIRLS HOSTEL FIRST FLOOOR A Wing", "Girls Hostel"},
            {"c4:0a:cb:25:96:5", "GIRLS HOSTEL FIRST FLOOOR B Wing", "Girls Hostel"},
            {"c4:0a:cb:25:db:6", "Girls Hostel First Floor C Wing", "Girls Hostel"},
            {"c4:0a:cb:2d:d6:7", "GIRLS HOSTEL SECOND FLOOOR B Wing", "Girls Hostel"},
            {"c4:0a:cb:25:c3:f", "GIRLS HOSTEL SECOND FLOOOR A Wing", "Girls Hostel"},
            {"c4:0a:cb:2d:7c:f", "GIRLS HOSTEL SECOND FLOOOR C Wing", "Girls Hostel"},
            {"c4:0a:cb:5c:11:6", "GIRLS HOSTEL THIRD FLOOOR A Wing", "Girls Hostel"},
            {"c4:0a:cb:25:af:1", "GIRLS HOSTEL THIRD FLOOOR B Wing", "Girls Hostel"},
            {"c4:0a:cb:25:cf:0", "Girl's Hostel 3'rd Floor C Wing", "Girls Hostel"},
            {"b0:00:b4:20:62:d", "Girls hostel 3rd Floor A Wing", "Girls Hostel"},
            {"2c:3e:cf:72:24:a", "Girls hostel 3rd Floor C Wing", "Girls Hostel"},
            {"b0:00:b4:20:69:4", "GIRLS HOSTEL 4TH FLOOOR A Wing", "Girls Hostel"},
            {"c4:0a:cb:5c:04:1", "Girl's Hostel 4'th Floor C Wing", "Girls Hostel"},
            {"2c:3e:cf:ca:f0:a", "Girls hostel 4th Floor A Wing", "Girls Hostel"},
            {"2c:3e:cf:ca:e7:8", "Girls hostel 4th Floor C Wing", "Girls Hostel"},

            {"64:a0:e7:f8:bf:6", "Boys Hostel Ground Floor A wing", "Boys Hostel"},
            {"c4:0a:cb:25:c8:1", "Boys Hostel Ground Floor C Wing", "Boys Hostel"},
            {"c4:0a:cb:5c:20:e", "BOYS HOSTEL GROUND FLOOR C-WING", "Boys Hostel"},
            {"2c:3e:cf:b6:c0:5", "Boys Hostel Ground floor Common Room", "Boys Hostel"},
            {"c4:0a:cb:2d:d5:7", "BH First floor A wing", "Boys Hostel"},
            {"c4:0a:cb:2d:ca:9", "BH First Floor B Wing", "Boys Hostel"},
            {"c4:0a:cb:25:f5:4", "BOYS HOSTEL 1ST FLOOR C WING", "Boys Hostel"},
            {"c4:0a:cb:25:e3:c", "BOYS HOSTEL 1ST FLOOR C WING", "Boys Hostel"},
            {"2c:3e:cf:8f:58:0", "Boys hostel 1st floor A wing", "Boys Hostel"},
            {"b0:00:b4:20:72:d", "Boys hostel 1st floor C wing", "Boys Hostel"},
            {"c4:0a:cb:25:ff:c", "Boys Hostel 2'nd floor A wing", "Boys Hostel"},
            {"c4:0a:cb:2d:d0:8", "Boys Hostel 2nd Floor B Wing", "Boys Hostel"},
            {"c4:0a:cb:2d:ce:4", "BOYS HOSTEL 2ND FLOOR C WING", "Boys Hostel"},
            {"c4:0a:cb:25:d1:8", "BOYS HOSTEL 2ND FLOOR C WING", "Boys Hostel"},
            {"b0:00:b4:20:6a:4", "Boys hostel 2nd floor A wing", "Boys Hostel"},
            {"2c:3e:cf:ca:eb:f", "Boys hostel 2nd floor C wing", "Boys Hostel"},
            {"c4:0a:cb:25:bb:1", "BH THIRD FLOOR A WING", "Boys Hostel"},
            {"c4:0a:cb:2d:7b:f", "Boys Hostel Third Floor B Wing", "Boys Hostel"},
            {"c4:0a:cb:25:fe:d", "Boys Hostel Third Floor C Wing", "Boys Hostel"},
            {"c4:0a:cb:2d:dd:3", "Boys Hostel Third Floor C Wing", "Boys Hostel"},
            {"b0:00:b4:20:72:c", "Boys hostel 3rd floor A wing", "Boys Hostel"},
            {"2c:3e:cf:8f:55:6", "Boys hostel 3rd floor C wing", "Boys Hostel"},
            {"c4:0a:cb:5c:0e:8", "BH fourth floor A wing", "Boys Hostel"},
            {"c4:0a:cb:2d:81:b", "BH fourth floor B wing", "Boys Hostel"},
            {"c4:0a:cb:2d:ca:8", "BOYS HOSTEL FORTH FLOOR C WING", "Boys Hostel"},
            {"c4:0a:cb:2d:98:3", "BOYS HOSTEL FORTH FLOOR C WING", "Boys Hostel"},
            {"b0:00:b4:20:72:a", "Boys hostel 4th floor A Wing", "Boys Hostel"},
            {"b0:00:b4:20:77:2", "Boys hostel 4th floor C Wing", "Boys Hostel"},
            {"c4:0a:cb:2d:dd:7", "Boys Hostel 5 Floor A Wing", "Boys Hostel"},
            {"c4:0a:cb:25:ff:7", "Boys Hostel Fifth Floor C wing", "Boys Hostel"},
            {"c4:0a:cb:2d:dd:c", "Boys Hostel Fifth Floor C Wing", "Boys Hostel"},
            {"b0:00:b4:20:69:d", "Boys hostel 5th floor A Wing", "Boys Hostel"},
            {"b0:00:b4:20:78:6", "Boys hostel 5th floor C Wing", "Boys Hostel"},
            {"64:a0:e7:91:43:9", "Boys Hostel 6 Floor A Wing", "Boys Hostel"},
            {"c4:0a:cb:2d:d5:8", "BOYS HOSTEL 6 TH FLOOR C WING", "Boys Hostel"},
            {"c4:0a:cb:2d:ce:3", "Boys Hostel Sixth Floor C wing", "Boys Hostel"},
            {"2c:3e:cf:ca:e4:f", "Boys hostel 6th floor A Wing", "Boys Hostel"},
            {"2c:3e:cf:8e:de:e", "Boys hostel 6th floor C Wing", "Boys Hostel"},
    };
}
